orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: iceipts/backend_boda
    docker: # Each job requires specifying an executor
      # (either docker, macos, or machine), see
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  publishAPISERVER:
    executor: docker-publisher

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish apiserver Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            ls
            pwd
            cd api-server
            docker build -t $IMAGE_NAME:apiserver .
            docker push $IMAGE_NAME:apiserver

  publishDNS_SERVER:
    executor: docker-publisher

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish apiserver Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            ls
            pwd
            cd dns-server
            docker build -t $IMAGE_NAME:dnsserver .
            docker push $IMAGE_NAME:dnsserver

  publishLOCATION_SERVER:
    executor: docker-publisher

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish apiserver Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            ls
            pwd
            cd location-server
            docker build -t $IMAGE_NAME:location .
            docker push $IMAGE_NAME:location

  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          command: |
            ssh -oStrictHostKeyChecking=no -v root@$DIGITAL_OCEAN_IP "./deploy.sh"

workflows:
  version: 2
  build-master:
    jobs:
      - publishAPISERVER:
          filters:
            branches:
              only:
                - master
      - publishDNS_SERVER:
          filters:
            branches:
              only:
                - master
      - publishLOCATION_SERVER:
          filters:
            branches:
              only:
                - master
      - pull-and-build:
          requires:
            - publishAPISERVER
            - publishDNS_SERVER
            - publishLOCATION_SERVER
          filters:
            branches:
              only:
                - master
